### ISSUE TITLE
[EV3Dev] Generate code using templates from autogen project

### ISSUE THREAD

**Issue by jabrena** [jabrena/ev3dev-lang-java#6]
It is necessary to create a template project to generate classes in automatic way in order to bind EV3Dev with the Java library.

Study this project in order to write templates for the library
https://github.com/ev3dev/ev3dev-lang/tree/develop/autogen

**Comment by jabrena** [comment]
Local configuration:

``` java
    "java": {
        "files": [
            "../ev3dev-lang-java/ev3dev.java",
            "../ev3dev-lang-java/spec_version.java"
        ],
        "templateDir": "java/templates/"
    },
```

**Comment by jabrena** [comment]
https://github.com/ev3dev/ev3dev-lang/issues/114

**Comment by rhempel** [comment]
So here's what you need to do - for changes to anything outside the `java` folder, clone the official `ev3dev-lang` repo and issue pull requests against it.
If the `java` code is actually different from `js` (I don't know the difference :-)) then coordinate with the `js` owner - @wasabifan
If this is a new language, I will create a `java` subfolder in the `ev3dev-lang` repo and point it at your repo as a submodule. You control the code - the `master branch` is the latest validated code, you should use `develop` for running changes and ongoing development, then merge into `master` for a new release. We'll update the `ev3dev-lang` repo to point at the new commit in `master`

**Comment by jabrena** [comment]
Yes Sir!!!

**Comment by rhempel** [comment]
Seems like lots of process, but as we add more language bindings I'd like to keep things organized...

**Comment by jabrena** [comment]
Dont't worry. in the office, I use the same kind of procedure. I prefer the processes to be all clean.

**Comment by jabrena** [comment]
@rhempel, I did my first pull request to the project.

I am thinking to create a java test project to test the physical references included in clases to a class generated dynamically with the templates.

How to get all methods from a tacho motor?

Cheers

**Comment by ddemidov** [comment]
Properties of tacho motor are listed in `spec.json` file: https://github.com/ev3dev/ev3dev-lang/blob/develop/autogen/spec.json#L19.

Here is an example of using the spec to generate C++ methods corresponding to the properties: https://github.com/ev3dev/ev3dev-lang/blob/develop/cpp/templates/generic-get-set.liquid. 

This template generates this section of the C++ header, corresponding to tacho-motor: https://github.com/ev3dev/ev3dev-lang/blob/develop/cpp/ev3dev.h#L586-L834 (as well as methods of other devices).

Same section is used to generate the test report here: https://github.com/ev3dev/ev3dev-lang/blob/develop/cpp/ev3dev.h#L586-L834 with the following template: https://github.com/ev3dev/ev3dev-lang/blob/develop/cpp/templates/generic_report_status.liquid.

**Comment by jabrena** [comment]
Many thanks @ddemidov this week, I will try to generate this structure using your example.

**Comment by jabrena** [comment]
@rhempel Tomorrow, I will continue with the process to generate a class using autogen system.

**Comment by jabrena** [comment]
Command to generate files from autogen:

``` bash
node autogen.js java
```

**Comment by jabrena** [comment]
How to update git submodules:

``` bash
git submodule foreach git pull origin master
git pull --recurse-submodules
git submodule update --recursive
```

**Comment by jabrena** [comment]
Generated ev3dev version.
I continue with attributes about tacho-motors

**Comment by jabrena** [comment]
Reading examples to improve template system for Java Binding:

Devices supported:
https://github.com/WasabiFan/ev3dev-lang-js/blob/master/motors.ts

Sensors:
https://github.com/WasabiFan/ev3dev-lang-js/blob/master/sensors.ts

**Comment by WasabiFan** [comment]
> How to update git submodules:

I would recommend not doing it this way if you are running that command on the whole ev3dev-lang repo. It is best to only update your submodule and not the others.

**Comment by jabrena** [comment]
Hi @WasabiFan, yes i am executing only the submodule about java:

``` bash
node autogen.js java
```

**Comment by jabrena** [comment]
Now, the class: "EV3DevConstants" is useful to be used for the classes in the project. If the project has to release, it is necessary to generate the class in order to check if something changed in spec.json.
