### ISSUE TITLE
Apply Singleton design pattern for Sound class

### ISSUE THREAD

**Issue by jabrena** [jabrena/ev3dev-lang-java#86]

**Comment by dlech** [comment]
I don't think this is a good idea for the battery class. In the future, there could be more than one battery. For example, some sensor multiplexers and motor controllers have their own battery that provides information back to the EV3. Instead, it would be better to add a factory method to get the "System" battery - the battery whose "scope" attribute (POWER_SUPPLY_PROP_SCOPE property) returns "System". Other batteries will have scope of "Device" or "Unknown".

**Comment by jabrena** [comment]
Sorry, I was going to close the issue but I am going to study in detail your idea because it has sense and it is useful your opinion. Feel free to discuss anything. This after lunch, I will study your comment. The rest of the API was tested and it runs.
